services:
  prometheus:
    image: quay.io/prometheus/prometheus:v3.2.1
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
  pushgateway:
    image: quay.io/prometheus/pushgateway
    container_name: pushgateway
    ports:
      - 9091:9091
    restart: unless-stopped
    command:
      - --web.listen-address=0.0.0.0:9091
  grafana:
    image: grafana/grafana:11.6.0
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_ANALYTICS_REPORTING_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
  weather:
    build: ./weather/
    container_name: weather
    restart: unless-stopped
    environment:
      - PUSHGATEWAY_URL=pushgateway:9091
      - PERIOD_SECONDS=5
volumes:
  prom_data:
